# theme: jekyll-theme-slate
lang: en-US
title: benjamin perkins, (aka @csharpguitar)
author: benjamin perkins
description: List<Solution> solutions = changes.Where(c => c.CeterisParibus != true)

# theme: jekyll-theme-tactile
